# Site settings
title: Khem Sattaur
email: khemsattaur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  khems.net is a place for me to share things I have done.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.khem.net" # the base hostname & protocol for your site
twitter_username: khemalien
github_username:  khems

# Build settings
markdown: kramdown
